// todo-angular/src/app/components/todo-item/todo-item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Todo } from '../../models/todo.model';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent {
  @Input() todo!: Todo;
  @Output() toggle = new EventEmitter<void>();
  @Output() edit = new EventEmitter<void>();
  @Output() delete = new EventEmitter<void>();

  formatDate(dateString?: string): string {
    if (!dateString) return '';
    const date = new Date(dateString);
    return date.toLocaleDateString('pt-BR') + ' ' +
           date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' });
  }
}


<div class="card mb-3 todo-item" [class.completed]="todo.completed">
  <div class="card-body">
    <div class="d-flex align-items-start">
      <!-- Checkbox -->
      <div class="me-3">
        <div class="custom-checkbox" (click)="toggle.emit()" style="cursor: pointer;">
          <i
            class="bi"
            [class.bi-check-circle-fill]="todo.completed"
            [class.bi-circle]="!todo.completed"
            [class.text-success]="todo.completed"
            [class.text-muted]="!todo.completed"
            style="font-size: 1.5rem;"
          ></i>
        </div>
      </div>

      <!-- Conteúdo -->
      <div class="flex-grow-1">
        <h5
          class="mb-1"
          [class.text-decoration-line-through]="todo.completed"
          [class.text-muted]="todo.completed"
        >
          {{ todo.title }}
        </h5>

        <p
          *ngIf="todo.description"
          class="text-muted mb-2"
          [class.text-decoration-line-through]="todo.completed"
        >
          {{ todo.description }}
        </p>

        <!-- Metadata -->
        <div class="small text-muted d-flex align-items-center">
          <i class="bi bi-calendar me-1"></i>
          <span>
            Criada em {{ formatDate(todo.createdAt) }}
          </span>
        </div>
      </div>

      <!-- Ações -->
      <div class="btn-group ms-3">
        <button
          class="btn btn-outline-primary btn-sm"
          (click)="edit.emit()"
          title="Editar"
        >
          <i class="bi bi-pencil"></i>
        </button>
        <button
          class="btn btn-outline-danger btn-sm"
          (click)="delete.emit()"
          title="Excluir"
        >
          <i class="bi bi-trash"></i>
        </button>
      </div>
    </div>
  </div>
</div>

// todo-react/src/components/TodoItem.jsx
import Card from 'react-bootstrap/Card'
import Button from 'react-bootstrap/Button'
import ButtonGroup from 'react-bootstrap/ButtonGroup'

function TodoItem({ todo, onToggle, onEdit, onDelete }) {
  const formatDate = (dateString) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    return date.toLocaleDateString('pt-BR') + ' ' + 
           date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })
  }

  return (
    <Card className={`mb-3 todo-item ${todo.completed ? 'completed' : ''}`}>
      <Card.Body>
        <div className="d-flex align-items-start">
          {/* Checkbox */}
          <div className="me-3">
            <div 
              className="custom-checkbox"
              onClick={onToggle}
              style={{ cursor: 'pointer' }}
            >
              <i 
                className="bi"
                style={{ fontSize: '1.5rem' }}
                class={todo.completed ? 'bi-check-circle-fill text-success' : 'bi-circle text-muted'}
              ></i>
            </div>
          </div>

          {/* Conteúdo */}
          <div className="flex-grow-1">
            <h5 
              className={`mb-1 ${todo.completed ? 'text-decoration-line-through text-muted' : ''}`}
            >
              {todo.title}
            </h5>
            
            {todo.description && (
              <p 
                className={`text-muted mb-2 ${todo.completed ? 'text-decoration-line-through' : ''}`}
              >
                {todo.description}
              </p>
            )}

            {/* Metadata */}
            <div className="small text-muted d-flex align-items-center">
              <i className="bi bi-calendar me-1"></i>
              <span>
                Criada em {formatDate(todo.createdAt)}
              </span>
            </div>
          </div>

          {/* Ações */}
          <ButtonGroup className="ms-3">
            <Button 
              variant="outline-primary" 
              size="sm"
              onClick={onEdit}
              title="Editar"
            >
              <i className="bi bi-pencil"></i>
            </Button>
            <Button 
              variant="outline-danger" 
              size="sm"
              onClick={onDelete}
              title="Excluir"
            >
              <i className="bi bi-trash"></i>
            </Button>
          </ButtonGroup>
        </div>
      </Card.Body>
    </Card>
  )
}

export default TodoItem
