// todo-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'TodoMaster - Angular';
}


<div class="d-flex flex-column min-vh-100">
  <app-header></app-header>

  <main class="container py-4 flex-grow-1">
    <router-outlet></router-outlet>
  </main>

  <app-footer></app-footer>
</div>

// todo-react/src/App.jsx
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import Header from './components/Header'
import Footer from './components/Footer'
import Home from './pages/Home'
import Todos from './pages/Todos'

function App() {
  return (
    <Router>
      <div className="d-flex flex-column min-vh-100">
        <Header />
        <main className="container py-4 flex-grow-1">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/todos" element={<Todos />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </Router>
  )
}

export default App
