// todo-angular/src/app/pages/todos/todos.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from '../../services/todo.service';
import { Todo } from '../../models/todo.model';

interface TodoStats {
  total: number;
  completed: number;
  pending: number;
}

@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html',
  styleUrls: ['./todos.component.scss']
})
export class TodosComponent implements OnInit {
  todos: Todo[] = [];
  loading = false;
  error: string | null = null;
  filter = 'all';
  editingTodo: Todo | null = null;
  showEditModal = false;

  constructor(private todoService: TodoService) { }

  ngOnInit(): void {
    this.fetchTodos();
  }

  fetchTodos(): void {
    this.loading = true;
    this.error = null;
    this.todoService.getAllTodos().subscribe({
      next: (data) => {
        this.todos = data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Erro ao carregar tarefas';
        console.error(err);
        this.loading = false;
      }
    });
  }

  handleAddTodo(todo: Todo): void {
    this.loading = true;
    this.todoService.createTodo(todo).subscribe({
      next: (data) => {
        this.todos = [data, ...this.todos];
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Erro ao criar tarefa';
        console.error(err);
        this.loading = false;
      }
    });
  }

  handleToggleTodo(id: number): void {
    this.todoService.toggleTodoCompletion(id).subscribe({
      next: (data) => {
        this.todos = this.todos.map(todo =>
          todo.id === id ? data : todo
        );
      },
      error: (err) => {
        console.error(err);
      }
    });
  }

  handleEditTodo(todo: Todo): void {
    this.editingTodo = { ...todo };
    this.showEditModal = true;
  }

  handleSaveEdit(): void {
    if (this.editingTodo && this.editingTodo.id) {
      this.todoService.updateTodo(this.editingTodo.id, this.editingTodo).subscribe({
        next: (data) => {
          this.todos = this.todos.map(todo =>
            todo.id === this.editingTodo!.id ? data : todo
          );
          this.closeEditModal();
        },
        error: (err) => {
          console.error(err);
        }
      });
    }
  }

  handleDeleteTodo(id: number): void {
    if (!confirm('Tem certeza que deseja excluir esta tarefa?')) return;

    this.todoService.deleteTodo(id).subscribe({
      next: () => {
        this.todos = this.todos.filter(todo => todo.id !== id);
      },
      error: (err) => {
        this.error = 'Erro ao excluir tarefa';
        console.error(err);
      }
    });
  }

  closeEditModal(): void {
    this.showEditModal = false;
    this.editingTodo = null;
  }

  onFilterChange(filter: string): void {
    this.filter = filter;
  }

  get stats(): TodoStats {
    return {
      total: this.todos.length,
      completed: this.todos.filter(todo => todo.completed).length,
      pending: this.todos.filter(todo => !todo.completed).length
    };
  }
}


<div class="container">
  <!-- Loading inicial -->
  <div *ngIf="loading && todos.length === 0" class="text-center py-5">
    <div class="spinner-border text-primary mb-3" role="status">
      <span class="visually-hidden">Carregando...</span>
    </div>
    <p class="text-muted">Carregando suas tarefas...</p>
  </div>

  <div *ngIf="!loading || todos.length > 0" class="todo-view">
    <!-- Header -->
    <div class="row mb-4 align-items-center">
      <div class="col-md-8">
        <h1 class="fw-bold mb-2">
          <i class="bi bi-list-check text-primary me-2"></i>
          Minhas Tarefas
        </h1>
        <p class="text-muted mb-0">
          Organize suas atividades e aumente sua produtividade
        </p>
      </div>
    </div>

    <!-- Formulário -->
    <app-todo-form
      [loading]="loading"
      (addTodo)="handleAddTodo($event)"
    ></app-todo-form>

    <!-- Lista -->
    <app-todo-list
      [todos]="todos"
      [filter]="filter"
      [stats]="stats"
      (filterChange)="onFilterChange($event)"
      (toggleTodo)="handleToggleTodo($event)"
      (editTodo)="handleEditTodo($event)"
      (deleteTodo)="handleDeleteTodo($event)"
    ></app-todo-list>
  </div>
</div>

<!-- Modal de edição -->
<div
  class="modal fade"
  [class.show]="showEditModal"
  [style.display]="showEditModal ? 'block' : 'none'"
  tabindex="-1"
  *ngIf="editingTodo"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <i class="bi bi-pencil-square text-primary me-2"></i>
          Editar Tarefa
        </h5>
        <button type="button" class="btn-close" (click)="closeEditModal()"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="editTitle" class="form-label">Título</label>
            <input
              type="text"
              class="form-control"
              id="editTitle"
              [(ngModel)]="editingTodo.title"
              name="title"
              required
            />
          </div>
          <div class="mb-3">
            <label for="editDescription" class="form-label">Descrição</label>
            <textarea
              class="form-control"
              id="editDescription"
              rows="3"
              [(ngModel)]="editingTodo.description"
              name="description"
            ></textarea>
          </div>
          <div class="form-check">
            <input
              type="checkbox"
              class="form-check-input"
              id="editCompleted"
              [(ngModel)]="editingTodo.completed"
              name="completed"
            />
            <label class="form-check-label" for="editCompleted">
              Tarefa concluída
            </label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="closeEditModal()">
          Cancelar
        </button>
        <button type="button" class="btn btn-primary" (click)="handleSaveEdit()">
          <i class="bi bi-save me-1"></i>
          Salvar Alterações
        </button>
      </div>
    </div>
  </div>
</div>
<div
  class="modal-backdrop fade"
  [class.show]="showEditModal"
  *ngIf="showEditModal"
  (click)="closeEditModal()"
></div>

// todo-react/src/pages/Todos.jsx
import { useState, useEffect } from 'react'
import Container from 'react-bootstrap/Container'
import Modal from 'react-bootstrap/Modal'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import Spinner from 'react-bootstrap/Spinner'
import TodoForm from '../components/TodoForm'
import TodoList from '../components/TodoList'
import api from '../services/api'

function Todos() {
  const [todos, setTodos] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [filter, setFilter] = useState('all')
  const [editingTodo, setEditingTodo] = useState(null)
  const [showEditModal, setShowEditModal] = useState(false)

  // Carregar tarefas
  const fetchTodos = async () => {
    setLoading(true)
    setError(null)
    try {
      const response = await api.get('/todos')
      setTodos(response.data)
    } catch (err) {
      setError('Erro ao carregar tarefas')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchTodos()
  }, [])

  // Adicionar tarefa
  const handleAddTodo = async (todoData) => {
    setLoading(true)
    try {
      const response = await api.post('/todos', todoData)
      setTodos(prev => [response.data, ...prev])
    } catch (err) {
      setError('Erro ao criar tarefa')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  // Alternar status
  const handleToggleTodo = async (id) => {
    try {
      const response = await api.patch(`/todos/${id}/toggle`)
      setTodos(prev => prev.map(todo => 
        todo.id === id ? response.data : todo
      ))
    } catch (err) {
      console.error(err)
    }
  }

  // Editar tarefa
  const handleEditTodo = (todo) => {
    setEditingTodo({ ...todo })
    setShowEditModal(true)
  }

  const handleSaveEdit = async () => {
    try {
      const response = await api.put(`/todos/${editingTodo.id}`, editingTodo)
      setTodos(prev => prev.map(todo => 
        todo.id === editingTodo.id ? response.data : todo
      ))
      setShowEditModal(false)
      setEditingTodo(null)
    } catch (err) {
      console.error(err)
    }
  }

  // Excluir tarefa
  const handleDeleteTodo = async (id) => {
    if (!window.confirm('Tem certeza que deseja excluir esta tarefa?')) return
    
    try {
      await api.delete(`/todos/${id}`)
      setTodos(prev => prev.filter(todo => todo.id !== id))
    } catch (err) {
      setError('Erro ao excluir tarefa')
      console.error(err)
    }
  }

  // Estatísticas
  const stats = {
    total: todos.length,
    completed: todos.filter(todo => todo.completed).length,
    pending: todos.filter(todo => !todo.completed).length
  }

  if (loading && todos.length === 0) {
    return (
      <Container className="text-center py-5">
        <Spinner animation="border" variant="primary" className="mb-3" />
        <p className="text-muted">Carregando suas tarefas...</p>
      </Container>
    )
  }

  return (
    <Container>
      <div className="todo-view">
        {/* Header */}
        <div className="row mb-4 align-items-center">
          <div className="col-md-8">
            <h1 className="fw-bold mb-2">
              <i className="bi bi-list-check text-primary me-2"></i>
              Minhas Tarefas
            </h1>
            <p className="text-muted mb-0">
              Organize suas atividades e aumente sua produtividade
            </p>
          </div>
        </div>

        {/* Formulário */}
        <TodoForm onAddTodo={handleAddTodo} loading={loading} />

        {/* Lista */}
        <TodoList
          todos={todos}
          filter={filter}
          onFilterChange={setFilter}
          onToggleTodo={handleToggleTodo}
          onEditTodo={handleEditTodo}
          onDeleteTodo={handleDeleteTodo}
          stats={stats}
        />

        {/* Modal de edição */}
        <Modal show={showEditModal} onHide={() => setShowEditModal(false)} centered>
          <Modal.Header closeButton>
            <Modal.Title>
              <i className="bi bi-pencil-square text-primary me-2"></i>
              Editar Tarefa
            </Modal.Title>
          </Modal.Header>
          <Modal.Body>
            {editingTodo && (
              <Form>
                <Form.Group className="mb-3">
                  <Form.Label>Título</Form.Label>
                  <Form.Control
                    type="text"
                    value={editingTodo.title}
                    onChange={(e) => setEditingTodo({ ...editingTodo, title: e.target.value })}
                    required
                  />
                </Form.Group>
                <Form.Group className="mb-3">
                  <Form.Label>Descrição</Form.Label>
                  <Form.Control
                    as="textarea"
                    rows={3}
                    value={editingTodo.description}
                    onChange={(e) => setEditingTodo({ ...editingTodo, description: e.target.value })}
                  />
                </Form.Group>
              </Form>
            )}
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={() => setShowEditModal(false)}>
              Cancelar
            </Button>
            <Button variant="primary" onClick={handleSaveEdit}>
              <i className="bi bi-save me-1"></i>
              Salvar Alterações
            </Button>
          </Modal.Footer>
        </Modal>
      </div>
    </Container>
  )
}

export default Todos
