// todo-react/src/components/TodoList.jsx
import TodoItem from './TodoItem'
import Button from 'react-bootstrap/Button'
import Card from 'react-bootstrap/Card'

function TodoList({ 
  todos, 
  filter, 
  onFilterChange, 
  onToggleTodo, 
  onEditTodo, 
  onDeleteTodo,
  stats 
}) {
  const filteredTodos = todos.filter(todo => {
    if (filter === 'completed') return todo.completed
    if (filter === 'pending') return !todo.completed
    return true
  })

  return (
    <div className="todo-list">
      {/* Filtros */}
      <div className="filters mb-4">
        <div className="btn-group" role="group">
          <Button
            variant={filter === 'all' ? 'primary' : 'outline-primary'}
            onClick={() => onFilterChange('all')}
            className="rounded"
          >
            <i className="bi bi-list-ul me-1"></i>
            Todas ({stats.total})
          </Button>
          <Button
            variant={filter === 'pending' ? 'primary' : 'outline-primary'}
            onClick={() => onFilterChange('pending')}
            className="rounded mx-2"
          >
            <i className="bi bi-clock me-1"></i>
            Pendentes ({stats.pending})
          </Button>
          <Button
            variant={filter === 'completed' ? 'primary' : 'outline-primary'}
            onClick={() => onFilterChange('completed')}
            className="rounded"
          >
            <i className="bi bi-check2-all me-1"></i>
            Concluídas ({stats.completed})
          </Button>
        </div>
      </div>

      {/* Estatísticas */}
      <Card className="mb-4 border-0" style={{
        background: 'linear-gradient(45deg, rgba(67, 97, 238, 0.1), rgba(58, 12, 163, 0.05))'
      }}>
        <Card.Body className="p-3">
          <div className="row text-center">
            <div className="col-4">
              <div className="fw-bold fs-4">{stats.total}</div>
              <small className="text-muted">Total</small>
            </div>
            <div className="col-4">
              <div className="fw-bold fs-4 text-success">{stats.completed}</div>
              <small className="text-muted">Concluídas</small>
            </div>
            <div className="col-4">
              <div className="fw-bold fs-4 text-warning">{stats.pending}</div>
              <small className="text-muted">Pendentes</small>
            </div>
          </div>
        </Card.Body>
      </Card>

      {/* Lista vazia */}
      {filteredTodos.length === 0 && (
        <div className="empty-state text-center py-5">
          <i className="bi bi-inbox display-1 text-muted mb-3"></i>
          <h4 className="fw-bold mb-2">
            {filter === 'completed' ? 'Nenhuma tarefa concluída ainda' : 'Nenhuma tarefa encontrada'}
          </h4>
          <p className="text-muted mb-4">
            {filter === 'all' ? 'Comece criando sua primeira tarefa!' : 
             filter === 'pending' ? 'Todas as tarefas estão concluídas!' : 
             'Complete algumas tarefas para vê-las aqui.'}
          </p>
          {filter !== 'all' && (
            <Button 
              variant="outline-primary"
              onClick={() => onFilterChange('all')}
            >
              <i className="bi bi-eye me-1"></i>
              Ver todas as tarefas
            </Button>
          )}
        </div>
      )}

      {/* Lista de tarefas */}
      {filteredTodos.map((todo, index) => (
        <div key={todo.id} className="fade-in" style={{ animationDelay: `${index * 0.1}s` }}>
          <TodoItem
            todo={todo}
            onToggle={() => onToggleTodo(todo.id)}
            onEdit={() => onEditTodo(todo)}
            onDelete={() => onDeleteTodo(todo.id)}
          />
        </div>
      ))}
    </div>
  )
}

export default TodoList

// todo-angular/src/app/components/todo-list/todo-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Todo } from '../../models/todo.model';

export interface TodoStats {
  total: number;
  completed: number;
  pending: number;
}

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.scss']
})
export class TodoListComponent {
  @Input() todos: Todo[] = [];
  @Input() filter: string = 'all';
  @Input() stats!: TodoStats;
  @Output() filterChange = new EventEmitter<string>();
  @Output() toggleTodo = new EventEmitter<number>();
  @Output() editTodo = new EventEmitter<Todo>();
  @Output() deleteTodo = new EventEmitter<number>();

  get filteredTodos(): Todo[] {
    return this.todos.filter(todo => {
      if (this.filter === 'completed') return todo.completed;
      if (this.filter === 'pending') return !todo.completed;
      return true;
    });
  }

  setFilter(filter: string): void {
    this.filter = filter;
    this.filterChange.emit(filter);
  }
}


<div class="todo-list">
  <!-- Filtros -->
  <div class="filters mb-4">
    <div class="btn-group" role="group">
      <button
        type="button"
        class="btn rounded"
        [class.btn-primary]="filter === 'all'"
        [class.btn-outline-primary]="filter !== 'all'"
        (click)="setFilter('all')"
      >
        <i class="bi bi-list-ul me-1"></i>
        Todas ({{ stats.total }})
      </button>
      <button
        type="button"
        class="btn rounded mx-2"
        [class.btn-primary]="filter === 'pending'"
        [class.btn-outline-primary]="filter !== 'pending'"
        (click)="setFilter('pending')"
      >
        <i class="bi bi-clock me-1"></i>
        Pendentes ({{ stats.pending }})
      </button>
      <button
        type="button"
        class="btn rounded"
        [class.btn-primary]="filter === 'completed'"
        [class.btn-outline-primary]="filter !== 'completed'"
        (click)="setFilter('completed')"
      >
        <i class="bi bi-check2-all me-1"></i>
        Concluídas ({{ stats.completed }})
      </button>
    </div>
  </div>

  <!-- Estatísticas -->
  <div class="card mb-4 border-0" style="background: linear-gradient(45deg, rgba(67, 97, 238, 0.1), rgba(58, 12, 163, 0.05))">
    <div class="card-body p-3">
      <div class="row text-center">
        <div class="col-4">
          <div class="fw-bold fs-4">{{ stats.total }}</div>
          <small class="text-muted">Total</small>
        </div>
        <div class="col-4">
          <div class="fw-bold fs-4 text-success">{{ stats.completed }}</div>
          <small class="text-muted">Concluídas</small>
        </div>
        <div class="col-4">
          <div class="fw-bold fs-4 text-warning">{{ stats.pending }}</div>
          <small class="text-muted">Pendentes</small>
        </div>
      </div>
    </div>
  </div>

  <!-- Lista vazia -->
  <div *ngIf="filteredTodos.length === 0" class="empty-state text-center py-5">
    <i class="bi bi-inbox display-1 text-muted mb-3"></i>
    <h4 class="fw-bold mb-2">
      {{ filter === 'completed' ? 'Nenhuma tarefa concluída ainda' : 'Nenhuma tarefa encontrada' }}
    </h4>
    <p class="text-muted mb-4">
      {{ filter === 'all' ? 'Comece criando sua primeira tarefa!' :
         filter === 'pending' ? 'Todas as tarefas estão concluídas!' :
         'Complete algumas tarefas para vê-las aqui.' }}
    </p>
    <button
      *ngIf="filter !== 'all'"
      class="btn btn-outline-primary"
      (click)="setFilter('all')"
    >
      <i class="bi bi-eye me-1"></i>
      Ver todas as tarefas
    </button>
  </div>

  <!-- Lista de tarefas -->
  <div *ngFor="let todo of filteredTodos; let i = index" class="fade-in" [style.animation-delay]="(i * 0.1) + 's'">
    <app-todo-item
      [todo]="todo"
      (toggle)="toggleTodo.emit(todo.id!)"
      (edit)="editTodo.emit(todo)"
      (delete)="deleteTodo.emit(todo.id!)"
    ></app-todo-item>
  </div>
</div>
